---
- name: Download Splunk Universal Forwarder RPM package
  ansible.builtin.get_url:
    url: "{{ splunk_forwarder_rpm_url }}"
    dest: "{{ splunk_forwarder_rpm_path }}"
    mode: "0644"

- name: Install Splunk Universal Forwarder RPM package
  ansible.builtin.dnf:
    name: "{{ splunk_forwarder_rpm_path }}"
    state: present
    disable_gpg_check: true
