---
zabbix_version: "7.4"

zabbix_agent_package: "zabbix-agent2"
zabbix_agent_service: "zabbix-agent2"
zabbix_agent_config_path: "/etc/zabbix/zabbix_agent2.conf"

zabbix_agent_server: "127.0.0.1"
zabbix_agent_server_active: "127.0.0.1"

zabbix_agent_hostname: "{{ inventory_hostname }}"

zabbix_agent_listen_port: 10050
zabbix_agent_timeout: 10

zabbix_agent_log_file: "/var/log/zabbix/zabbix_agent2.log"
zabbix_agent_log_file_size: 10

zabbix_repo_rpm_amazon_2023: >-
  https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/amazonlinux/2023/noarch/zabbix-release-latest-{{ zabbix_version }}.amzn2023.noarch.rpm

zabbix_repo_deb_ubuntu: >-
  https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu{{ ansible_facts['distribution_version'] }}_all.deb
